name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup and start back
        working-directory: ./server
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn format
      - run: yarn lint
      - run: yarn build
      - run: yarn test

      - name: Setup and generate front
        working-directory: ./client
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      # - run: yarn types:openapi
      - run: yarn build
      - run: yarn test
