name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Setup and start back
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
        run: yarn install --frozen-lockfile
        run: yarn format
        run: yarn lint
        run: yarn build
        run: yarn test
        run: yarn start
        working-directory: ./server

      # - uses: actions/checkout@v2
      # - name: Setup and generate front
      #   working-directory: ./client
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - run: yarn install --frozen-lockfile
      # - run: yarn types:openapi
      # - run: yarn build
      # - run: yarn test
